### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by Earnestly** [AdaCore/xmlada#3]
- **gprbuild** GPRBUILD Pro 18.0w (19940713) (x86_64-pc-linux-gnu)
- **gcc** 6.2.1 20160830 (GCC) 

```
% make PROCESSORS="$(nproc)" relocatable
[...]
Build Libraries
   [gprlib]       xmlada_unicode.lexch

raised CONSTRAINT_ERROR : g-dyntab.adb:259 access check failed
gprbuild: could not build library for project xmlada_unicode
make: *** [Makefile:58: relocatable] Error 4
```

**Comment by Earnestly** [comment]
This issue is still present on:

* `GPRBUILD Pro 18.0w (19940713) (x86_64-pc-linux-gnu)`
* `gcc (GCC) 6.2.1 20160830`

I found `/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/adainclude/g-dyntab.adb:259` references this piece of code within the `Set_Item` procedure:

```ada
      subtype Allocated_Table_T is
        Table_Type (T.Table'First .. Table_Index_Type (T.P.Max + 1));
```

Is there perhaps a known issue with my version of GNAT (gcc) or is this a problem in xmlada itself?  The error message is a little vague (the lack of a path component to the file makes me unsure to which it is refering), and nothing in the xmlada codebase appears to call `Set_Item` directly.

PS: I've run this again with `GPRBUILD_OPTIONS=-v` and removed `PROCESSORS="$(nproc)"` in the hope to get a better error message and found this:

```
/usr/bin/gcc -c -x ada -gnatA -fPIC -gnatwua -gnaty -gnatQ -O2 -gnatn -gnatec= [...]
Changing to object directory of "XmlAda_Unicode": "/home/earnest/build/store/ada-xmlada-git/src/xmlada/unicode/obj/relocatable/"
Changing to object directory of "XmlAda_UnicodeChanging to object directory of "XmlAda_Unicode": "/home/earnest/build/store/ada-xmlada-git/src/xmlada/unicode/obj/static/"
": "/home/earnest/build/store/ada-xmlada-git/src/xmlada/unicode/obj/static-pic/"
/usr/lib/gprbuild/gprlib xmlada_unicode.lexch
/usr/lib/gprbuild/gprlib xmlada_unicode.lexch
/usr/lib/gprbuild/gprlib xmlada_unicode.lexch
/usr/bin/ar cr /home/earnest/build/store/ada-xmlada-git/src/xmlada/unicode/lib/static-pic/libxmlada_unicode.a [...] /home/earnest/build/store/ada-xmlada-git/src/xmlada/unicode/obj/static-pic/unicode-names-ol_chiki.o

raised CONSTRAINT_ERROR : g-dyntab.adb:259 access check failed
gprbuild: could not build library for project xmlada_unicode
make: *** [Makefile:58: relocatable] Error 4
make: *** Waiting for unfinished jobs....
```

Still not something I can seem to understand, but that ar command contains a very large string of directories and arguments.  Calculating this with `wc -c` returns 8142 bytes (probably including a trailing newline) which is still far lower than `getconf ARG_MAX` of `2097152` bytes, so it can't be that.

Either way I do not know enough about Ada to really solve this on my own.

**Comment by t-14** [comment]
Hi. While we can't reproduce the problem, examining the logs we see some output that is potentially problematic. We will investigate.

"-bargs" is not a switch you can pass like that, since *everything* past -bargs is considered binder switches (not just "-E"). You'll need to tweak the makefile a bit to be able to  pass -bargs. But let us first investigate some funny things we can observe.

**Comment by Earnestly** [comment]
For what it's worth, the `gprbuild` I'm using was built using the bootstrap proceedure, see the routine here: http://sprunge.us/LDXb?sh

I'll try see if I can get `-bargs -E` to work as it might help me find where exactly this execption is coming from.

**Comment by Earnestly** [comment]
If there are any possible environment differences you can think of to test, please feel free to ask.

**Comment by t-14** [comment]
Hi. Can you try with a new gprbuild? We never could reproduce the issue, but there was one anomaly we've fixed in https://github.com/AdaCore/gprbuild/commit/36edd4616d4083dc6cf2508c9a45f3ed5664f86d

I am wondering if rather than being just a display glitch this issue could exceed the output buffer size and cause a crash.

**Comment by Earnestly** [comment]
I've tried gprbuild from the last commit https://github.com/AdaCore/gprbuild/commit/14e2b68d499d56010a5d9ff5fe498b155ae21f1f and unfortunately still see the same error.

**Comment by t-14** [comment]
Shame :( Unfortunately without reproducing it we don't have much to go by. There is nothing obviously wrong with the configuration options, but I am not a compiler specialist.

Perhaps you can try building the tools with debug info and extended exception information by adding -g to CFLAGS and "-bargs -E" to GNATMAKEFLAGS. This should give backtrace on exception. Maybe the backtrace will give us additional information?

**Comment by Earnestly** [comment]
Since `-bargs -E` is positional, I don't think it will be so simple.  Mostly because the expansion of them in `./bootstrap.sh` is as follows:

```bash
for prg in $BIN_PROGS; do
    ${GNATMAKE} $INC_FLAGS ${prg}-main -o $prg $CFLAGS $GNATMAKEFLAGS -largs gpr_imports.o
done

for prg in $LIBEXEC_PROGS; do
    ${GNATMAKE} $INC_FLAGS $prg $CFLAGS $GNATMAKEFLAGS -largs gpr_imports.o
done
```

I can certainly enable debug information (which is typically `-g -fvar-tracking-assignments`) but will that be enough?  Any suggestions how I could sneak `-bargs -E` into `GNATMAKEFLAGS`?

**Comment by t-14** [comment]
> Since -bargs -E is positional, I don't think it will be so simple. Mostly because the expansion of them in ./bootstrap.sh is as follows

Should be fine, the tail of the command will become "-bargs -E -largs gpr_imports.o" which should be properly understood by gnatmake.

GNATMAKEFLAGS processing is definitely broken, thanks for the suggested patch, we'll apply it (and fix the help message regarding --).

> there still appears to be no -bargs -E in the output of the following commands

It won't show up in the output, but what you should see is that calls to gnatbind now include -E.

**Comment by Earnestly** [comment]
Ah I'm silly, yes of course it shows up as including `-E` just as you wrote.  I don't know why I was expecting `bargs`, thanks.

Now with gprbuild built including debug symbols and `-E` I get a little more information:

```
gprbuild -j0 -m -v -p -XLIBRARY_TYPE=relocatable -XBUILD=Production -XPROCESSORS=0 xmlada.gpr
Changing to object directory of "XmlAda_Unicode": "/home/earnest/build/store/ada-xmlada-git/src/xmlada/unicode/obj/relocatable/"
/usr/lib/gprbuild/gprlib xmlada_unicode.lexch

Execution terminated by unhandled exception
raised CONSTRAINT_ERROR : g-dyntab.adb:259 access check failed
Call stack traceback locations:
0x462624 0x5a1863 0x5ad30c 0x5bb297 0x5c0536 0x406089 0x7fb866be628f 0x406108 0xfffffffffffffffe
gprbuild: could not build library for project xmlada_unicode
```

Can I (or you) use those traceback locations in a meaningful manner?  They do seem to be constant across multiple attempts.

---

Something I did notice which seemed a little wrong is that my host seems to be detected incorrectly (my `gcc -dumpmachine` returns `x86_64-pc-linux-gnu`):

```
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
```

Although as this is only used to check for differences when assigning `--target` to `GPROPTS` it shouldn't matter.

**Comment by t-14** [comment]
> Can I (or you) use those traceback locations in a meaningful manner?

Yes, you can symbolize them using either gdb or addr2line utility that's part of binutils. In either case you should feed to the tool the failing executable to extract debug info from (note it's not gprbuild itself but a separate helper tool called gprlib)

**Comment by Earnestly** [comment]
```
% addr2line -e /usr/lib/gprbuild/gprlib 0x462624 0x5a1863 0x5ad30c 0x5bb297 0x5c0536 0x406089 0x7fb866be628f 0x406108 0xfffffffffffffffe
```

With a little sed and some magic, I've tried to produce some of a useful backtrace through the code highlighting the jumps with `=>`:

```
/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/adainclude/g-dyntab.adb:259
      subtype Allocated_Table_T is
=>      Table_Type (T.Table'First .. Table_Index_Type (T.P.Max + 1));
      --  A constrained table subtype one element larger than the currently
      --  allocated table.

/home/earnest/build/store/gprbuild-bootstrap-git/src/gprbuild/src/gpr_util.adb:502
      Name_2 := No_Path;
      Tempdir.Create_Temp_File (Resp_File, Name => Name_1);
=>    Record_Temp_File (null, Name_1);

      if Format = GNU or else Format = GCC_GNU then

/home/earnest/build/store/gprbuild-bootstrap-git/src/gprbuild/./src/gprlib-build_shared_lib.adb:294 (discriminator 6)
         begin
=>          Create_Response_File
              (Format            => Resp_File_Format,
               Objects           => Arguments (First_Object .. Last_Object),
               Other_Arguments   => Options,
               Resp_File_Options => Response_File_Switches.all,

/home/earnest/build/store/gprbuild-bootstrap-git/src/gprbuild/./src/gprlib-build_shared_lib.adb:482
      --  Now that the table has been filled, call Build

=>    Build (Library_Version_Path.all);

      --  Create symbolic link, if appropriate

/home/earnest/build/store/gprbuild-bootstrap-git/src/gprbuild/src/gprlib.adb:2608
      Process_Static;

   elsif not No_Create then
=>    Process_Shared;
   end if;

/home/earnest/build/store/gprbuild-bootstrap-git/src/gprbuild/b~gprlib.adb:710
      Initialize (SEH'Address);
      adainit;
=>    Ada_Main_Program;
      adafinal;
      Finalize;

??:0            0x7fb866be628f 
??:?            0x406108
??:0            0xfffffffffffffffe
```

**Comment by Earnestly** [comment]
No change after trying again since: https://github.com/AdaCore/gprbuild/commit/4bc35e6f549d4fd287595623686dd90e34c1a24e

*Would you like this issue to move to https://github.com/AdaCore/gprbuild/issues instead?*

**Comment by pmderodat** [comment]
I managed to reproduce the issue. All it takes is the GNAT GPL 2016 release for `x86_64-linux` and development branches for both XML-Ada and GPRbuild. Here is a script that does everything required:

```sh
#! /bin/sh

set -x
set -e

ROOT="$PWD"
PREFIX="$ROOT/install"


# Remove artifacts from previous run
rm -rf xmlada gprbuild install


# Install GNAT GPL in $PREFIX and use it
wget -O gnat-gpl-2016-x86_64-linux-bin.tar.gz \
    http://mirrors.cdn.adacore.com/art/573f240ac7a447edfe0316a5
tar xf gnat-gpl-2016-x86_64-linux-bin.tar.gz
(cd gnat-gpl-2016-x86_64-linux-bin &&
    ./doinstall <<EOF

$PREFIX
y
y
y
EOF
)
export PATH="$PREFIX/bin:$PATH"


# Get development branches for XML/Ada and GPRbuild
git clone https://github.com/AdaCore/xmlada.git
git clone https://github.com/AdaCore/gprbuild.git


# Build GPRbuild using the bootstrap script
(cd gprbuild &&
    ./bootstrap.sh --prefix="$PREFIX" --with-xmlada="$ROOT/xmlada")


# Try to build XML/Ada: it should crash:
#    raised CONSTRAINT_ERROR : g-dyntab.adb:259 access check failed
#    gprbuild: could not build library for project xmlada_unicode
#    make: *** [Makefile:58: relocatable] Error 4
(cd xmlada && ./configure && make)

```

Note: I tested it on one of our production server. ;-)

**Comment by t-14** [comment]
The current understanding is that it has been fixed in gcc-7 by the following commit: https://github.com/gcc-mirror/gcc/commit/43572e7bdc7ab21e1538e7322a56b5610df8e1a3

We will check if we can install some kind of a workaround in gprbuild to make it work with gcc-6/gnatgpl-2016.

**Comment by Earnestly** [comment]
Ah, wonderful.  I don't mind waiting as my distribution will provide the next version gcc soon after upstream releases it. 

My only concern is that many distributions aren't even on gcc 6 yet which does somewhat limit the use of `gprbuild` unless they themselves include  other workarounds already.

**Comment by t-14** [comment]
Unfortunately I don't think we'll be able to support the Ada compiler from gcc versions prior to 6, since the runtime has evolved too much and we need some recent functionality. But we might be able to support gcc 6 at least.

**Comment by okellogg** [comment]
> The current understanding is that it has been fixed in gcc-7 by the following commit:
> gcc-mirror/gcc@43572e7

Thanks for the pointer.
I ran into this crash in a [TclAdaShell build](https://sourceforge.net/p/tcladashell/bugs/7/#6cf4).
I simply made a local copy of the updated g-dyntab.{ads,adb} (renaming them to g_dynamic_tables.{ads,adb} and commenting out the `pragma Compiler_Unit_Warning`) and adjusted the code to the changed name. This solved the problem for me.

**Comment by simonjwright** [comment]
Building the exact same sources as @okellogg on

* macOS Sierra with GCC 6.1.0 and gprbuild c5c26c2683fcdd9c1fc684274faaad1b30c762e1 [with a patch to compilers.xml]
* likewise, with GNAT GPL 2016
* Debian jessie (amd64), which is basically GCC 4.9 & gprbuild GPL 2014)

gave no problems.

**Comment by simonjwright** [comment]
This issue (which is really, I think, a gprbuild issue) should have been resolved by AdaCore/gprbuild/pull/22.

**Comment by Earnestly** [comment]
Issue still present on GCC 7.1

**Comment by simonjwright** [comment]
You need a development gprbuild later than 27 February (or before 18 July 2016). See AdaCore/gprbuild#22.

**Comment by simonjwright** [comment]
I just rebuilt AdaCore/gprbuild@a9a2a5b3 (the commit before the one which fixes this problem) with GCC 7.1.0; built a dynamic library without problems.

**Comment by Earnestly** [comment]
@simonjwright May I ask what you're doing?

**Comment by simonjwright** [comment]
@Earnestly, I’ve been building a [7.1.0 release for macOS](https://sourceforge.net/projects/gnuada/files/GNAT_GCC%20Mac%20OS%20X/7.1.0/native-2016/); remembered this issue, decided to check whether GCC 7 really does build a working gprbuild even without the patch I provided. It does.

I’m wondering what gprbuild you were using which still had the issue?

**Comment by Earnestly** [comment]
I'm using a gprbuild bootstrapped from the latest commit https://github.com/AdaCore/gprbuild/commit/9af55aba02544ce2c8819a06d3f6651b6b0495ab (time of writing) to build xmlada.  This is all happening on Linux which may be where the difference lies.  @pmderodat tells me that the test case (above) is still causing issues on 7.1.

The maintainer is apparently still on vacation so we will likely have to wait.  My involvement at this point is updating the bug report if the issue persists after any major component changes (such as GCC).

**Comment by simonjwright** [comment]
I think it has to be Linux vs macOS; the test case worked fine here.

Darwin’s `install` doesn’t work the way `bootstrap.sh` thinks it ought to. I’ll raise an issue about that over on AdaCore/gprbuild.

When I was building xmlada for GCC 7.1.0, before I’d built the GCC 6.1.0 gprbuild, I set my PATH to gcc-7.1.0-bin:gcc-6.1.0-bin:... and the existing gprbuild used the new compiler without issues.

**Comment by pmderodat** [comment]
Hi @Earnestly 

So now that GCC 7 is available on my Arch machine, I tried to reproduce.
```sh
$ gcc -v |& tail -n1
gcc version 7.1.1 20170528 (GCC)
$ which gprbuild
which: no gprbuild in ([…])

$ rm -rf /tmp/foo && mkdir /tmp/foo && cd /tmp/foo
$ export PATH=/tmp/foo/install/bin:$PATH

$ git clone git@github.com:AdaCore/gprbuild
$ git clone git@github.com:AdaCore/xmlada

$ (cd gprbuild && \
    ./bootstrap.sh --prefix=/tmp/foo/install)
$ (cd xmlada && \
    ./configure --prefix=/tmp/foo/install && \
    make PROCESSORS="$(nproc)" relocatable)
```
All commands completed successfuly, so I cannot reproduce the crash at all. Do you still reproduce? If so, do you have a different build procedure?

The precise commits I used were https://github.com/AdaCore/gprbuild/commit/18e2bc01b811de8ecba5b92a83bca07495411306 and https://github.com/AdaCore/xmlada/commit/b1be3aa7a2582209cd295f6769dcf5c826e30cf3.

**Comment by Earnestly** [comment]
I'm glad to report that the issue seems to be resolved, I can now continue and clean up any rough corners.  Thanks for all your efforts in replicating the failure.  I'll leave more detailed information about my procedure used and environment for posterity:

---

* gprbuild https://github.com/AdaCore/gprbuild/commit/18e2bc01b811de8ecba5b92a83bca07495411306
* xmlada https://github.com/AdaCore/xmlada/commit/b1be3aa7a2582209cd295f6769dcf5c826e30cf3

* gcc version 7.1.1 20170516 (GCC)

> Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
> Thread model: posix

* `CFLAGS` `-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -g -fvar-tracking-assignments`

#### gprbuild bootstrap
```sh
    cd gprbuild

    sed -i 's/libexec/lib/g' doinstall gprbuild.gpr \
        share/gprconfig/compilers.xml \
        share/gprconfig/linker.xml \
        share/gprconfig/gnat.xml

    export GNATMAKEFLAGS="-j$(nproc)"
    export DESTDIR="$srcdir"/bootstrap
    ./bootstrap.sh --prefix=/usr --libexecdir=/lib --with-xmlada="$srcdir"/xmlada
```

#### xmlada
```sh
    cd xmlada
    ./configure --prefix=/usr --libexecdir=/lib --enable-shared
    make PROCESSORS="$(nproc)" relocatable
```

**Comment by pmderodat** [comment]
Ok, thanks!
